"""AI contract agent — Bedrock DeepSeek V3 integration for contract generation."""

from __future__ import annotations

import json
from typing import Any
import boto3
from ..config import config


CONTRACT_AGENT_SYSTEM = """You are Rostr Contracts, an AI contract agent powered by Artispreneur. 
You specialize in music industry contracts: recording deals, management agreements, 
production contracts, publishing splits, booking agreements, licensing, and more.

When a user describes a contract need:
1. Identify the most relevant contract template from the available categories
2. Extract key terms from their description (names, percentages, dates, amounts)
3. Draft a complete, professionally worded contract using industry-standard language
4. Flag any missing critical fields and ask the user to clarify
5. Always remind the user this is not legal advice — consult an attorney for final review

Contract categories: Recording, Production, Management, Performance, Representation, 
Licensing, Marketing, Sponsorship, Collaboration, Business, Release.

Respond in a helpful, professional tone. Be specific about terms. 
Format your response so contract sections are clearly labeled."""


def generate_contract(
    template_slug: str,
    fields: dict[str, Any],
    chat_input: str | None = None,
) -> dict[str, Any]:
    """Generate a contract using Bedrock DeepSeek V3."""
    client = boto3.client("bedrock-runtime", region_name=config.region)

    user_prompt = f"""Generate a music industry contract using the template: {template_slug}.

Fields provided:
{json.dumps(fields, indent=2)}

{f"Additional instructions from the user: {chat_input}" if chat_input else ""}

Please produce a complete, professionally worded contract. Include all standard clauses 
for this type of agreement. Use the field values where provided, and fill in reasonable 
defaults for any missing standard clauses."""

    try:
        response = client.invoke_model(
            modelId=config.bedrock_model,
            contentType="application/json",
            accept="application/json",
            body=json.dumps({
                "messages": [
                    {"role": "system", "content": CONTRACT_AGENT_SYSTEM},
                    {"role": "user", "content": user_prompt},
                ],
                "temperature": 0.3,
                "max_tokens": 4096,
            }),
        )
        body = json.loads(response["body"].read())
        content = body.get("choices", [{}])[0].get("message", {}).get("content", "")
        return {"content": content, "model": config.bedrock_model}
    except Exception as e:
        # Fallback: return structured template-based contract
        return {
            "content": _fallback_contract(template_slug, fields, chat_input),
            "model": "fallback-template",
            "note": f"Bedrock unavailable ({str(e)[:100]}), using template fallback",
        }


def _fallback_contract(
    template_slug: str,
    fields: dict[str, Any],
    chat_input: str | None = None,
) -> str:
    """Generate a contract from template when Bedrock is unavailable."""
    template_names = {
        "influencer-agreement": "Artist Influencer Agreement",
        "production-agreement": "Music Production Agreement",
        "artist-management-agreement": "Artist Management Agreement",
        "artist-label-agreement": "Artist Recording Contract",
        "sponsorship-agreement": "Sponsorship Agreement",
        "band-booking-agreement": "Band Booking Agreement",
        "artist-venue-agreement": "Artist/Venue Agreement",
        "dj-booking-agreement": "DJ Booking Agreement",
        "artist-agent-agreement": "Artist-Agent Agreement",
        "licensing-agreement": "Music Licensing Agreement",
        "collaboration-agreement": "Artist Collaboration Agreement",
        "work-for-hire": "Work for Hire Agreement",
        "producer-talent-agreement": "Master Producer-Talent Agreement",
        "studio-time": "Studio Time Contract",
    }
    title = template_names.get(template_slug, template_slug.replace("-", " ").title())

    lines = [
        f"{'='*60}",
        f"  {title.upper()}",
        f"  Generated by Rostr Contracts — Powered by Artispreneur",
        f"  Date: {__import__('datetime').datetime.now().strftime('%B %d, %Y')}",
        f"{'='*60}",
        "",
        "THIS AGREEMENT is made and entered into as of the date set forth above,",
        "by and between the parties identified below.",
        "",
    ]

    # Render fields
    for key, value in fields.items():
        label = key.replace("_", " ").title()
        val = value if value else ""
        lines.append(f"  {label}: {val}")

    lines.extend([
        "",
        "--- TERMS AND CONDITIONS ---",
        "",
        "1. The parties agree to the terms set forth above.",
        "2. This agreement shall be governed by the laws of the state specified.",
        "3. Any disputes shall be resolved through binding arbitration.",
        "4. This agreement represents the entire understanding between the parties.",
        "",
        f"Additional context: {chat_input}" if chat_input else "",
        "",
        "--- DISCLAIMER ---",
        "This document was generated by Rostr Contracts AI and is provided for",
        "informational purposes only. It does not constitute legal advice.",
        "Please consult with a qualified attorney before signing.",
        "",
        "--- END OF CONTRACT ---",
    ])

    return "\n".join(lines)


def chat(message: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
    """Chat with the AI contract agent about a contract query."""
    client = boto3.client("bedrock-runtime", region_name=config.region)

    ctx_str = json.dumps(context) if context else "No additional context"

    try:
        response = client.invoke_model(
            modelId=config.bedrock_model,
            contentType="application/json",
            accept="application/json",
            body=json.dumps({
                "messages": [
                    {"role": "system", "content": CONTRACT_AGENT_SYSTEM},
                    {"role": "user", "content": f"Context: {ctx_str}\n\nUser: {message}"},
                ],
                "temperature": 0.5,
                "max_tokens": 2048,
            }),
        )
        body = json.loads(response["body"].read())
        reply = body.get("choices", [{}])[0].get("message", {}).get("content", "")
        return {"reply": reply, "model": config.bedrock_model}
    except Exception as e:
        return {
            "reply": f"I understand you need help with a contract. Please describe the type of agreement and key terms (names, dates, percentages, amounts) and I'll draft it for you.\n\n(Note: AI backend unavailable — {str(e)[:80]})",
            "model": "fallback",
        }
