"use client"

import { useState, useEffect, useMemo } from "react"
import { useSearchParams, useRouter } from "next/navigation"
import Link from "next/link"
import { Header } from "@/components/header"
import { contractTemplates, type ContractTemplate } from "@/lib/contracts"
import {
  Sparkles, ArrowRight, Download, FileText, Check, Loader2, ChevronLeft, Shield,
} from "lucide-react"

export default function GeneratePage() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const templateSlug = searchParams.get("template")
  const template = useMemo(() => contractTemplates.find((c) => c.slug === templateSlug), [templateSlug])

  const [step, setStep] = useState<"chat" | "form" | "generated">("chat")
  const [chatInput, setChatInput] = useState("")
  const [chatMessages, setChatMessages] = useState<{ role: "user" | "agent"; text: string }[]>([])
  const [formData, setFormData] = useState<Record<string, string>>({})
  const [generating, setGenerating] = useState(false)
  const [generatedPdf, setGeneratedPdf] = useState(false)
  const [copied, setCopied] = useState(false)
  const [error, setError] = useState("")

  // If template is pre-selected, auto-fill some context
  useEffect(() => {
    if (template) {
      setChatMessages([
        { role: "agent", text: `I've loaded the **${template.name}** template (${template.category}). This contract covers: ${template.description}\n\nYou can describe your specific terms below, or click "Fill Form" to fill in the fields manually.` },
      ])
    }
  }, [template])

  const handleChatSend = () => {
    if (!chatInput.trim()) return
    const userMsg = chatInput.trim()
    setChatMessages((prev) => [...prev, { role: "user", text: userMsg }])
    setChatInput("")
    setGenerating(true)
    setError("")

    // Simulate AI response
    setTimeout(() => {
      const responses = [
        `Got it. I'll draft the contract with these terms:\n\n${userMsg.length > 80 ? "• " + userMsg.slice(0, 80) + "..." : "• " + userMsg}\n\nI've identified the key fields and legal terms. Ready to generate the final PDF. Click "Generate Contract" when ready.`,
        `Processing your request. Based on what you've described, I'm structuring a ${template?.category || "music"} agreement with industry-standard language. The AI has identified ${template?.fields.length || "all"} relevant fields.\n\nWould you like to review the field values before generating?`,
      ]
      setGenerating(false)
      setChatMessages((prev) => [...prev, { role: "agent", text: responses[Math.floor(Math.random() * responses.length)] }])
    }, 1500 + Math.random() * 1000)
  }

  const handleFormFill = () => {
    setStep("form")
  }

  const handleFieldChange = (fieldId: string, value: string) => {
    setFormData((prev) => ({ ...prev, [fieldId]: value }))
  }

  const handleGenerate = () => {
    setGenerating(true)
    setError("")
    setTimeout(() => {
      setGenerating(false)
      setGeneratedPdf(true)
      setStep("generated")

      // Save to localStorage
      try {
        const saved = JSON.parse(localStorage.getItem("artispreneur_saved_contracts") || "[]")
        saved.unshift({
          id: Date.now().toString(),
          title: template?.name || "Generated Contract",
          template_slug: template?.slug || "",
          fields: formData,
          created_at: new Date().toISOString(),
        })
        localStorage.setItem("artispreneur_saved_contracts", JSON.stringify(saved))
      } catch {}
    }, 2000 + Math.random() * 1000)
  }

  const handleCopyText = () => {
    const text = generateContractText()
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const generateContractText = () => {
    if (!template) return "No template selected."
    const lines = [
      `═══════════════════════════════════════════════`,
      `  ${template.name.toUpperCase()}`,
      `  Category: ${template.category}`,
      `  Generated by Rostr Contracts — Powered by Artispreneur`,
      `  Date: ${new Date().toLocaleDateString()}`,
      `═══════════════════════════════════════════════`,
      ``,
    ]
    template.fields.forEach((f) => {
      const val = formData[f.id] || chatMessages.filter((m) => m.role === "user").map((m) => m.text).join(" ").slice(0, 200) || "[NOT SPECIFIED]"
      lines.push(`${f.label}: ${val}`)
    })
    lines.push(``, `--- END OF CONTRACT ---`, `Generated using Rostr Contracts AI Agent`, `artispreneur.com/contracts`)
    return lines.join("\n")
  }

  const inputStyle: React.CSSProperties = {
    width: "100%", padding: "12px 14px",
    background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 8, color: "#FAFAFA", fontFamily: "inherit", fontSize: 14,
    outline: "none", transition: "border-color 200ms",
  }

  return (
    <div style={{ backgroundColor: "#050505", minHeight: "100vh" }}>
      <Header />

      {/* Breadcrumb */}
      <div className="container mx-auto px-4 py-4">
        <Link href="/" className="flex items-center gap-2 text-[12px] font-medium" style={{ color: "rgba(250,250,250,0.4)" }}>
          <ChevronLeft className="w-3.5 h-3.5" /> Back to Dashboard
        </Link>
      </div>

      <section className="container mx-auto px-4 py-4" style={{ maxWidth: 800 }}>
        {/* Title */}
        <div className="mb-8">
          <h1 className="text-2xl md:text-3xl font-bold text-white mb-2" style={{ fontFamily: "var(--font-serif)" }}>
            {template ? template.name : "Generate a Contract"}
          </h1>
          {template && (
            <p className="text-[13px]" style={{ color: "rgba(250,250,250,0.4)" }}>
              {template.category} · {template.fields.length} fields · AI-powered generation
            </p>
          )}
        </div>

        {step !== "generated" && (
          <>
            {/* AI Chat Interface */}
            {step === "chat" && (
              <div style={{
                background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)",
                borderRadius: 12, overflow: "hidden",
              }}>
                {/* Chat messages */}
                <div style={{
                  padding: "20px 24px", maxHeight: 400, overflowY: "auto",
                  display: "flex", flexDirection: "column", gap: 14,
                }}>
                  {chatMessages.map((msg, i) => (
                    <div key={i} style={{
                      display: "flex",
                      justifyContent: msg.role === "user" ? "flex-end" : "flex-start",
                    }}>
                      {msg.role === "agent" ? (
                        <div style={{ display: "flex", gap: 10, alignItems: "flex-start", maxWidth: "85%" }}>
                          <div style={{
                            width: 26, height: 26, borderRadius: "50%",
                            background: "rgba(201,162,39,0.2)", display: "flex",
                            alignItems: "center", justifyContent: "center",
                            flexShrink: 0, marginTop: 2,
                          }}>
                            <Sparkles className="w-3 h-3" style={{ color: "#C9A227" }} />
                          </div>
                          <div style={{
                            padding: "11px 15px", borderRadius: "10px 10px 10px 2px",
                            background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.06)",
                            color: "#FAFAFA", fontSize: 13, lineHeight: 1.7,
                            whiteSpace: "pre-wrap",
                          }}>
                            {msg.text.split("**").map((part, j) =>
                              j % 2 === 1 ? <strong key={j} style={{ color: "#C9A227" }}>{part}</strong> : part
                            )}
                          </div>
                        </div>
                      ) : (
                        <div style={{
                          maxWidth: "75%", padding: "10px 14px",
                          borderRadius: "10px 10px 2px 10px",
                          background: "#CC0000", color: "#fff", fontSize: 13, lineHeight: 1.6,
                        }}>
                          {msg.text}
                        </div>
                      )}
                    </div>
                  ))}
                </div>

                {/* Chat input */}
                <div style={{
                  borderTop: "1px solid rgba(255,255,255,0.06)", padding: "14px 20px",
                  display: "flex", gap: 10, alignItems: "flex-end",
                }}>
                  <textarea
                    rows={2}
                    placeholder="Describe the contract terms you need..."
                    value={chatInput}
                    onChange={(e) => setChatInput(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter" && !e.shiftKey) {
                        e.preventDefault()
                        handleChatSend()
                      }
                    }}
                    style={{
                      flex: 1, background: "rgba(255,255,255,0.03)",
                      border: "1px solid rgba(255,255,255,0.08)", borderRadius: 8,
                      padding: "10px 14px", color: "#FAFAFA", fontFamily: "inherit",
                      fontSize: 13, resize: "none", outline: "none",
                      lineHeight: 1.6,
                    }}
                    onFocus={(e) => { e.currentTarget.style.borderColor = "rgba(201,162,39,0.4)" }}
                    onBlur={(e) => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.08)" }}
                  />
                  <div className="flex flex-col gap-2">
                    <button
                      onClick={handleChatSend}
                      disabled={!chatInput.trim() || generating}
                      style={{
                        background: chatInput.trim() && !generating ? "#CC0000" : "rgba(255,255,255,0.05)",
                        color: chatInput.trim() && !generating ? "#fff" : "rgba(250,250,250,0.2)",
                        border: "none", borderRadius: 8, padding: "8px 16px",
                        fontSize: 12, fontWeight: 700, cursor: chatInput.trim() ? "pointer" : "not-allowed",
                        fontFamily: "inherit", display: "flex", alignItems: "center", gap: 6,
                      }}>
                      {generating ? (
                        <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      ) : (
                        <>Send <ArrowRight className="w-3 h-3" /></>
                      )}
                    </button>
                    <button
                      onClick={handleFormFill}
                      style={{
                        background: "transparent", color: "rgba(250,250,250,0.4)",
                        border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8,
                        padding: "8px 12px", fontSize: 11, fontWeight: 600,
                        cursor: "pointer", fontFamily: "inherit",
                      }}>
                      Fill Form
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Form Mode */}
            {step === "form" && template && (
              <div style={{
                background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)",
                borderRadius: 12, padding: "24px 28px",
              }}>
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-[15px] font-bold text-white">Contract Fields</h3>
                  <button
                    onClick={() => setStep("chat")}
                    style={{
                      background: "transparent", color: "#C9A227", border: "none",
                      fontSize: 12, fontWeight: 600, cursor: "pointer", fontFamily: "inherit",
                    }}>
                    ← Back to Chat
                  </button>
                </div>

                <div style={{
                  display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(240px, 1fr))",
                  gap: 14, marginBottom: 24,
                }}>
                  {template.fields.map((field) => (
                    <div key={field.id}>
                      <label style={{
                        display: "block", fontSize: 11, fontWeight: 600,
                        color: "rgba(250,250,250,0.45)", marginBottom: 6,
                        letterSpacing: "0.02em", textTransform: "uppercase",
                      }}>
                        {field.label} {field.required ? "*" : ""}
                      </label>
                      {field.type === "textarea" ? (
                        <textarea
                          rows={2}
                          style={{ ...inputStyle, resize: "none", fontSize: 13 }}
                          placeholder={field.placeholder || ""}
                          value={formData[field.id] || ""}
                          onChange={(e) => handleFieldChange(field.id, e.target.value)}
                          onFocus={(e) => { e.currentTarget.style.borderColor = "rgba(201,162,39,0.4)" }}
                          onBlur={(e) => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.08)" }}
                        />
                      ) : field.type === "select" && field.options ? (
                        <select
                          style={inputStyle}
                          value={formData[field.id] || ""}
                          onChange={(e) => handleFieldChange(field.id, e.target.value)}
                        >
                          <option value="">Select...</option>
                          {field.options.map((opt) => (
                            <option key={opt} value={opt}>{opt}</option>
                          ))}
                        </select>
                      ) : (
                        <input
                          type={field.type === "date" ? "date" : field.type === "number" ? "number" : field.type === "email" ? "email" : "text"}
                          style={inputStyle}
                          placeholder={field.placeholder || ""}
                          value={formData[field.id] || ""}
                          onChange={(e) => handleFieldChange(field.id, e.target.value)}
                          onFocus={(e) => { e.currentTarget.style.borderColor = "rgba(201,162,39,0.4)" }}
                          onBlur={(e) => { e.currentTarget.style.borderColor = "rgba(255,255,255,0.08)" }}
                        />
                      )}
                      {field.description && (
                        <p className="text-[10px] mt-1" style={{ color: "rgba(250,250,250,0.2)" }}>
                          {field.description}
                        </p>
                      )}
                    </div>
                  ))}
                </div>

                <button
                  onClick={handleGenerate}
                  disabled={generating}
                  style={{
                    width: "100%", background: generating ? "rgba(255,255,255,0.05)" : "#CC0000",
                    color: generating ? "rgba(250,250,250,0.2)" : "#fff",
                    border: "none", borderRadius: 8, padding: "14px 0",
                    fontSize: 14, fontWeight: 700, cursor: generating ? "not-allowed" : "pointer",
                    fontFamily: "inherit", display: "flex", alignItems: "center",
                    justifyContent: "center", gap: 8,
                  }}>
                  {generating ? (
                    <><Loader2 className="w-4 h-4 animate-spin" /> Generating Contract...</>
                  ) : (
                    <><Sparkles className="w-4 h-4" /> Generate Contract</>
                  )}
                </button>
              </div>
            )}
          </>
        )}

        {/* Generated Result */}
        {step === "generated" && (
          <div style={{ animation: "fade-in 0.5s ease both" }}>
            {/* Success card */}
            <div style={{
              background: "rgba(201,162,39,0.05)", border: "1px solid rgba(201,162,39,0.15)",
              borderRadius: 12, padding: "28px 32px", textAlign: "center", marginBottom: 24,
            }}>
              <div style={{
                width: 56, height: 56, borderRadius: "50%",
                background: "rgba(201,162,39,0.15)", margin: "0 auto 16px",
                display: "flex", alignItems: "center", justifyContent: "center",
              }}>
                <Check className="w-7 h-7" style={{ color: "#C9A227" }} />
              </div>
              <h2 style={{ fontFamily: "var(--font-serif)", fontSize: 24, fontWeight: 700, color: "#FAFAFA", marginBottom: 8 }}>
                Contract Generated
              </h2>
              <p className="text-[13px] leading-relaxed" style={{ color: "rgba(250,250,250,0.4)", maxWidth: 480, margin: "0 auto 20px" }}>
                Your <strong style={{ color: "#C9A227" }}>{template?.name || "contract"}</strong> has been generated with all specified terms. Copy the text or download as a PDF.
              </p>
              <div className="flex gap-3 justify-center flex-wrap">
                <button
                  onClick={handleCopyText}
                  style={{
                    background: copied ? "#1A7F4B" : "#CC0000",
                    color: "#fff", border: "none", borderRadius: 8, padding: "12px 24px",
                    fontSize: 13, fontWeight: 700, cursor: "pointer", fontFamily: "inherit",
                    display: "flex", alignItems: "center", gap: 8, transition: "all 200ms",
                  }}>
                  {copied ? <><Check className="w-4 h-4" /> Copied!</> : <><FileText className="w-4 h-4" /> Copy Contract Text</>}
                </button>
                <button
                  onClick={() => window.print()}
                  style={{
                    background: "transparent", color: "#FAFAFA",
                    border: "1px solid rgba(255,255,255,0.12)", borderRadius: 8,
                    padding: "12px 24px", fontSize: 13, fontWeight: 600,
                    cursor: "pointer", fontFamily: "inherit",
                    display: "flex", alignItems: "center", gap: 8,
                  }}>
                  <Download className="w-4 h-4" /> Print / Save PDF
                </button>
              </div>
            </div>

            {/* Contract Preview */}
            <div style={{
              background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)",
              borderRadius: 12, padding: "32px 36px",
            }}>
              <div className="flex items-center gap-2 mb-6 pb-4 border-b border-white/8">
                <Shield className="w-4 h-4" style={{ color: "#C9A227" }} />
                <span className="text-[11px] font-bold tracking-[0.08em] uppercase" style={{ color: "rgba(250,250,250,0.3)", fontFamily: "var(--font-mono)" }}>
                  Contract Preview
                </span>
              </div>
              <pre style={{
                fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.8,
                color: "rgba(250,250,250,0.6)", whiteSpace: "pre-wrap",
                background: "transparent", padding: 0, margin: 0,
              }}>
                {generateContractText()}
              </pre>
            </div>

            {/* Next steps */}
            <div style={{
              display: "flex", justifyContent: "center", gap: 12, marginTop: 24, flexWrap: "wrap",
            }}>
              <Link href="/generate">
                <button style={{
                  background: "transparent", color: "#C9A227",
                  border: "1px solid rgba(201,162,39,0.3)", borderRadius: 8,
                  padding: "10px 20px", fontSize: 13, fontWeight: 600,
                  cursor: "pointer", fontFamily: "inherit",
                }}>
                  Generate Another
                </button>
              </Link>
              <Link href="/">
                <button style={{
                  background: "transparent", color: "rgba(250,250,250,0.4)",
                  border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8,
                  padding: "10px 20px", fontSize: 13, fontWeight: 600,
                  cursor: "pointer", fontFamily: "inherit",
                }}>
                  Back to Dashboard
                </button>
              </Link>
            </div>
          </div>
        )}

        {error && (
          <div style={{
            background: "rgba(239,68,68,0.1)", border: "1px solid rgba(239,68,68,0.2)",
            borderRadius: 8, padding: "12px 16px", color: "#EF4444", fontSize: 13,
            marginTop: 12,
          }}>
            {error}
          </div>
        )}
      </section>
    </div>
  )
}
