export interface ContractTemplate {
  id: string
  slug: string
  name: string
  description: string
  category: string
  fields: ContractField[]
  pdfUrl: string
}

export interface ContractField {
  id: string
  name: string
  label: string
  type: "text" | "email" | "date" | "number" | "textarea" | "select" | "currency" | "percentage"
  placeholder?: string
  description?: string
  required: boolean
  options?: string[]
}

export const contractTemplates: ContractTemplate[] = [
  {
    id: "1",
    slug: "influencer-agreement",
    name: "Artist Influencer Agreement",
    description:
      "A sponsorship agreement between a sponsor and an influencer for promoting goods through social media channels.",
    category: "Marketing",
    pdfUrl: "/contracts/influencer-agreement.pdf",
    fields: [
      {
        id: "effective_date",
        name: "effective_date",
        label: "Effective Date",
        type: "date",
        required: false,
        description: "The date this agreement becomes effective",
      },
      {
        id: "sponsor_name",
        name: "sponsor_name",
        label: "Sponsor Name",
        type: "text",
        required: false,
        placeholder: "Enter sponsor/company name",
      },
      {
        id: "sponsor_state",
        name: "sponsor_state",
        label: "Sponsor State of Incorporation",
        type: "text",
        required: false,
        placeholder: "e.g., Delaware",
      },
      {
        id: "sponsor_address",
        name: "sponsor_address",
        label: "Sponsor Address",
        type: "textarea",
        required: false,
        placeholder: "Full business address",
      },
      { id: "sponsor_email", name: "sponsor_email", label: "Sponsor Email", type: "email", required: false },
      { id: "influencer_name", name: "influencer_name", label: "Influencer Name", type: "text", required: false },
      {
        id: "influencer_address",
        name: "influencer_address",
        label: "Influencer Address",
        type: "textarea",
        required: false,
      },
      { id: "influencer_email", name: "influencer_email", label: "Influencer Email", type: "email", required: false },
      {
        id: "goods_description",
        name: "goods_description",
        label: "Description of Goods",
        type: "textarea",
        required: false,
        description: "Describe the products/goods being promoted",
      },
      {
        id: "social_platforms",
        name: "social_platforms",
        label: "Social Media Platforms",
        type: "textarea",
        required: false,
        placeholder: "e.g., Instagram, TikTok, YouTube",
      },
      {
        id: "display_channels",
        name: "display_channels",
        label: "Display Channels",
        type: "textarea",
        required: false,
        description: "Channels where goods will be displayed",
      },
      { id: "termination_date", name: "termination_date", label: "Termination Date", type: "date", required: false },
      {
        id: "specific_terms",
        name: "specific_terms",
        label: "Specific Terms",
        type: "textarea",
        required: false,
        description: "Any additional specific terms for the sponsorship",
      },
      { id: "payment_amount", name: "payment_amount", label: "Payment Amount", type: "currency", required: false },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
        description: "When and how payments will be made",
      },
      {
        id: "jurisdiction_county",
        name: "jurisdiction_county",
        label: "Jurisdiction County",
        type: "text",
        required: false,
        placeholder: "County for legal jurisdiction",
      },
    ],
  },
  {
    id: "2",
    slug: "production-agreement",
    name: "Music Production Agreement",
    description: "Agreement between a music producer and client for the production of music recordings.",
    category: "Production",
    pdfUrl: "/contracts/production-agreement.pdf",
    fields: [
      { id: "state", name: "state", label: "State", type: "text", required: false, placeholder: "e.g., California" },
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "producer_name", name: "producer_name", label: "Producer Name", type: "text", required: false },
      {
        id: "producer_address",
        name: "producer_address",
        label: "Producer Address",
        type: "textarea",
        required: false,
      },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      {
        id: "production_services",
        name: "production_services",
        label: "Production Services",
        type: "textarea",
        required: false,
        description: "Describe the specific production services to be provided",
      },
      { id: "commencement_date", name: "commencement_date", label: "Commencement Date", type: "date", required: false },
      { id: "fixed_fee", name: "fixed_fee", label: "Fixed Fee", type: "currency", required: false },
      {
        id: "specifications",
        name: "specifications",
        label: "Project Specifications",
        type: "textarea",
        required: false,
        description: "Required specifications for the project",
      },
      {
        id: "invoice_period",
        name: "invoice_period",
        label: "Invoice Payment Period",
        type: "text",
        required: false,
        placeholder: "e.g., 30 days",
      },
      {
        id: "payment_method",
        name: "payment_method",
        label: "Payment Method",
        type: "text",
        required: false,
        placeholder: "e.g., Bank transfer, PayPal",
      },
      {
        id: "late_interest_rate",
        name: "late_interest_rate",
        label: "Late Payment Interest Rate",
        type: "percentage",
        required: false,
      },
      {
        id: "royalties",
        name: "royalties",
        label: "Royalties",
        type: "textarea",
        required: false,
        description: "Describe any royalty arrangements",
      },
      { id: "producer_email", name: "producer_email", label: "Producer Email", type: "email", required: false },
      { id: "client_email", name: "client_email", label: "Client Email", type: "email", required: false },
    ],
  },
  {
    id: "3",
    slug: "artist-management-agreement",
    name: "Artist Management Agreement",
    description: "Comprehensive agreement between an artist and manager for career management services.",
    category: "Management",
    pdfUrl: "/contracts/artist-management-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "manager_name", name: "manager_name", label: "Manager Name", type: "text", required: false },
      {
        id: "initial_term",
        name: "initial_term",
        label: "Initial Term",
        type: "text",
        required: false,
        placeholder: "e.g., 6 months",
      },
      {
        id: "option_periods",
        name: "option_periods",
        label: "Option Periods",
        type: "text",
        required: false,
        placeholder: "e.g., Two 3-year periods",
      },
      {
        id: "commission_rate",
        name: "commission_rate",
        label: "Commission Rate",
        type: "percentage",
        required: false,
        placeholder: "e.g., 20%",
      },
      {
        id: "expense_approval_limit",
        name: "expense_approval_limit",
        label: "Expense Approval Limit",
        type: "currency",
        required: false,
        description: "Amount above which artist approval is needed",
      },
      {
        id: "post_term_commission_rate",
        name: "post_term_commission_rate",
        label: "Post-Term Commission Rate",
        type: "percentage",
        required: false,
      },
      {
        id: "post_term_period",
        name: "post_term_period",
        label: "Post-Term Period",
        type: "text",
        required: false,
        placeholder: "e.g., 1 year",
      },
      {
        id: "notice_days",
        name: "notice_days",
        label: "Notice Period (Days)",
        type: "number",
        required: false,
        placeholder: "e.g., 30",
      },
      {
        id: "arbitration_location",
        name: "arbitration_location",
        label: "Arbitration Location",
        type: "text",
        required: false,
      },
      {
        id: "governing_law_state",
        name: "governing_law_state",
        label: "Governing Law State",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "4",
    slug: "artist-label-agreement",
    name: "Artist Recording Contract",
    description: "Recording contract between an artist and a record label for producing commercial sound records.",
    category: "Recording",
    pdfUrl: "/contracts/artist-label-agreement.pdf",
    fields: [
      { id: "agreement_day", name: "agreement_day", label: "Agreement Day", type: "number", required: false },
      { id: "agreement_month", name: "agreement_month", label: "Agreement Month", type: "text", required: false },
      { id: "agreement_year", name: "agreement_year", label: "Agreement Year", type: "number", required: false },
      { id: "company_name", name: "company_name", label: "Company/Label Name", type: "text", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      {
        id: "agreement_period",
        name: "agreement_period",
        label: "Agreement Period",
        type: "text",
        required: false,
        placeholder: "e.g., 2 years",
      },
      {
        id: "minimum_selections",
        name: "minimum_selections",
        label: "Minimum Selections to Record",
        type: "number",
        required: false,
      },
      {
        id: "royalty_cents",
        name: "royalty_cents",
        label: "Royalty (Cents per Record)",
        type: "number",
        required: false,
      },
      {
        id: "payment_period_1",
        name: "payment_period_1",
        label: "First Payment Period Month",
        type: "text",
        required: false,
      },
      {
        id: "payment_period_1_end",
        name: "payment_period_1_end",
        label: "First Period End Date",
        type: "text",
        required: false,
      },
      {
        id: "payment_period_2",
        name: "payment_period_2",
        label: "Second Payment Period Month",
        type: "text",
        required: false,
      },
      {
        id: "payment_period_2_end",
        name: "payment_period_2_end",
        label: "Second Period End Date",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "5",
    slug: "sponsorship-agreement",
    name: "Sponsorship Agreement",
    description: "Agreement between an event organizer and sponsor for event sponsorship with promotional rights.",
    category: "Sponsorship",
    pdfUrl: "/contracts/sponsorship-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "organizer_name", name: "organizer_name", label: "Organizer Name", type: "text", required: false },
      { id: "organizer_state", name: "organizer_state", label: "Organizer State", type: "text", required: false },
      {
        id: "organizer_address",
        name: "organizer_address",
        label: "Organizer Address",
        type: "textarea",
        required: false,
      },
      { id: "sponsor_name", name: "sponsor_name", label: "Sponsor Name", type: "text", required: false },
      { id: "sponsor_state", name: "sponsor_state", label: "Sponsor State", type: "text", required: false },
      { id: "sponsor_address", name: "sponsor_address", label: "Sponsor Address", type: "textarea", required: false },
      { id: "event_type", name: "event_type", label: "Event Type", type: "text", required: false },
      { id: "event_time", name: "event_time", label: "Event Time/Date", type: "text", required: false },
      { id: "event_location", name: "event_location", label: "Event Location", type: "text", required: false },
      { id: "event_name", name: "event_name", label: "Event Name", type: "text", required: false },
      {
        id: "sponsorship_fee",
        name: "sponsorship_fee",
        label: "Total Sponsorship Fee",
        type: "currency",
        required: false,
      },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
      },
      { id: "term_end_date", name: "term_end_date", label: "Term End Date", type: "date", required: false },
    ],
  },
  {
    id: "6",
    slug: "band-booking-agreement",
    name: "Band Booking Agreement",
    description: "Performance contract between a band and venue/operator for live performances.",
    category: "Performance",
    pdfUrl: "/contracts/band-booking-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "operator_name", name: "operator_name", label: "Operator/Venue Name", type: "text", required: false },
      { id: "band_name", name: "band_name", label: "Band Name", type: "text", required: false },
      { id: "venue_name", name: "venue_name", label: "Venue Name", type: "text", required: false },
      { id: "venue_address", name: "venue_address", label: "Venue Address", type: "textarea", required: false },
      { id: "show_date", name: "show_date", label: "Show Date", type: "date", required: false },
      {
        id: "show_time",
        name: "show_time",
        label: "Show Time",
        type: "text",
        required: false,
        placeholder: "e.g., 9 PM",
      },
      {
        id: "minimum_duration",
        name: "minimum_duration",
        label: "Minimum Performance Duration (minutes)",
        type: "number",
        required: false,
      },
      { id: "total_fee", name: "total_fee", label: "Total Fee", type: "currency", required: false },
      { id: "payment_method", name: "payment_method", label: "Payment Method", type: "text", required: false },
      { id: "guest_tickets", name: "guest_tickets", label: "Number of Guest Tickets", type: "number", required: false },
      { id: "meals_provided", name: "meals_provided", label: "Meals/Buyout Details", type: "text", required: false },
      {
        id: "buyout_amount",
        name: "buyout_amount",
        label: "Buyout Amount Per Person",
        type: "currency",
        required: false,
      },
    ],
  },
  {
    id: "7",
    slug: "artist-venue-agreement",
    name: "Artist/Venue Agreement",
    description: "Comprehensive agreement between an artist and venue for performances at events.",
    category: "Performance",
    pdfUrl: "/contracts/artist-venue-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "venue_name", name: "venue_name", label: "Venue Name", type: "text", required: false },
      {
        id: "venue_organisation",
        name: "venue_organisation",
        label: "Venue Organisation",
        type: "text",
        required: false,
      },
      { id: "venue_address", name: "venue_address", label: "Venue Address", type: "textarea", required: false },
      { id: "venue_abn", name: "venue_abn", label: "Venue ABN", type: "text", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "artist_address", name: "artist_address", label: "Artist Address", type: "textarea", required: false },
      {
        id: "artist_contact_mobile",
        name: "artist_contact_mobile",
        label: "Artist Mobile",
        type: "text",
        required: false,
      },
      {
        id: "artist_contact_email",
        name: "artist_contact_email",
        label: "Artist Email",
        type: "email",
        required: false,
      },
      {
        id: "artist_representative",
        name: "artist_representative",
        label: "Artist Representative Name",
        type: "text",
        required: false,
      },
      { id: "performance_date", name: "performance_date", label: "Performance Date", type: "date", required: false },
      {
        id: "performance_duration",
        name: "performance_duration",
        label: "Performance Duration",
        type: "text",
        required: false,
      },
      { id: "fee_amount", name: "fee_amount", label: "Artist Fee", type: "currency", required: false },
      {
        id: "venue_manager_details",
        name: "venue_manager_details",
        label: "Venue Manager Details",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "8",
    slug: "dj-booking-agreement",
    name: "DJ Booking Agreement",
    description: "Service agreement between a DJ and client for DJ services at events.",
    category: "Performance",
    pdfUrl: "/contracts/dj-booking-agreement.pdf",
    fields: [
      { id: "state", name: "state", label: "State", type: "text", required: false },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      { id: "dj_name", name: "dj_name", label: "DJ Name", type: "text", required: false },
      { id: "dj_address", name: "dj_address", label: "DJ Address", type: "textarea", required: false },
      { id: "event_date", name: "event_date", label: "Event Date", type: "date", required: false },
      { id: "event_time", name: "event_time", label: "Event Time", type: "text", required: false },
      {
        id: "services_description",
        name: "services_description",
        label: "Services Description",
        type: "textarea",
        required: false,
      },
      { id: "total_hours", name: "total_hours", label: "Total Hours", type: "number", required: false },
      { id: "setup_time", name: "setup_time", label: "Setup Time Before Event", type: "text", required: false },
      { id: "venue_location", name: "venue_location", label: "Venue Location", type: "textarea", required: false },
      {
        id: "payment_structure",
        name: "payment_structure",
        label: "Payment Structure",
        type: "textarea",
        required: false,
      },
      { id: "retainer_fee", name: "retainer_fee", label: "Retainer Fee", type: "currency", required: false },
      {
        id: "overtime_rate",
        name: "overtime_rate",
        label: "Overtime Rate (per hour)",
        type: "currency",
        required: false,
      },
      { id: "late_fee", name: "late_fee", label: "Late Payment Fee", type: "currency", required: false },
      {
        id: "cancellation_notice",
        name: "cancellation_notice",
        label: "Cancellation Notice Period",
        type: "text",
        required: false,
      },
      {
        id: "cancellation_penalty",
        name: "cancellation_penalty",
        label: "Cancellation Penalty",
        type: "currency",
        required: false,
      },
    ],
  },
  {
    id: "9",
    slug: "agent-agreement",
    name: "Artist-Agent Agreement",
    description: "Agreement between an artist and agent for representation and marketing of artistic work.",
    category: "Representation",
    pdfUrl: "/contracts/agent-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "artist_address", name: "artist_address", label: "Artist Address", type: "textarea", required: false },
      { id: "agent_name", name: "agent_name", label: "Agent Name", type: "text", required: false },
      { id: "agent_address", name: "agent_address", label: "Agent Address", type: "textarea", required: false },
      { id: "agent_company", name: "agent_company", label: "Agent Company", type: "text", required: false },
      {
        id: "territory",
        name: "territory",
        label: "Territory",
        type: "text",
        required: false,
        placeholder: "e.g., United States, Worldwide",
      },
      {
        id: "commission_rate",
        name: "commission_rate",
        label: "Commission Rate",
        type: "percentage",
        required: false,
      },
      { id: "agreement_term", name: "agreement_term", label: "Agreement Term", type: "text", required: false },
      {
        id: "termination_notice",
        name: "termination_notice",
        label: "Termination Notice Period",
        type: "text",
        required: false,
      },
      {
        id: "governing_law_state",
        name: "governing_law_state",
        label: "Governing Law State",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "10",
    slug: "licensing-agreement",
    name: "Music Licensing Agreement",
    description: "Agreement for licensing music rights between a licensor and licensee.",
    category: "Licensing",
    pdfUrl: "/contracts/licensing-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "licensor_name", name: "licensor_name", label: "Licensor Name", type: "text", required: false },
      {
        id: "licensor_address",
        name: "licensor_address",
        label: "Licensor Address",
        type: "textarea",
        required: false,
      },
      { id: "licensee_name", name: "licensee_name", label: "Licensee Name", type: "text", required: false },
      {
        id: "licensee_address",
        name: "licensee_address",
        label: "Licensee Address",
        type: "textarea",
        required: false,
      },
      { id: "work_title", name: "work_title", label: "Work Title", type: "text", required: false },
      {
        id: "work_description",
        name: "work_description",
        label: "Work Description",
        type: "textarea",
        required: false,
      },
      {
        id: "license_type",
        name: "license_type",
        label: "License Type",
        type: "text",
        required: false,
        placeholder: "e.g., Exclusive, Non-exclusive",
      },
      { id: "territory", name: "territory", label: "Territory", type: "text", required: false },
      { id: "license_fee", name: "license_fee", label: "License Fee", type: "currency", required: false },
      { id: "royalty_rate", name: "royalty_rate", label: "Royalty Rate", type: "percentage", required: false },
      { id: "license_term", name: "license_term", label: "License Term", type: "text", required: false },
      {
        id: "permitted_uses",
        name: "permitted_uses",
        label: "Permitted Uses",
        type: "textarea",
        required: false,
        description: "Describe how the licensed work may be used",
      },
    ],
  },
  {
    id: "11",
    slug: "collaboration-agreement",
    name: "Artist Collaboration Agreement",
    description: "Agreement between multiple artists for collaborative creative projects.",
    category: "Collaboration",
    pdfUrl: "/contracts/collaboration-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "artist_1_name", name: "artist_1_name", label: "First Artist Name", type: "text", required: false },
      {
        id: "artist_1_address",
        name: "artist_1_address",
        label: "First Artist Address",
        type: "textarea",
        required: false,
      },
      { id: "artist_2_name", name: "artist_2_name", label: "Second Artist Name", type: "text", required: false },
      {
        id: "artist_2_address",
        name: "artist_2_address",
        label: "Second Artist Address",
        type: "textarea",
        required: false,
      },
      {
        id: "project_description",
        name: "project_description",
        label: "Project Description",
        type: "textarea",
        required: false,
      },
      {
        id: "artist_1_contribution",
        name: "artist_1_contribution",
        label: "First Artist Contribution",
        type: "textarea",
        required: false,
      },
      {
        id: "artist_2_contribution",
        name: "artist_2_contribution",
        label: "Second Artist Contribution",
        type: "textarea",
        required: false,
      },
      {
        id: "ownership_split",
        name: "ownership_split",
        label: "Ownership Split",
        type: "text",
        required: false,
        placeholder: "e.g., 50/50",
      },
      {
        id: "revenue_split",
        name: "revenue_split",
        label: "Revenue Split",
        type: "text",
        required: false,
        placeholder: "e.g., 50/50",
      },
      { id: "project_deadline", name: "project_deadline", label: "Project Deadline", type: "date", required: false },
      {
        id: "credit_format",
        name: "credit_format",
        label: "Credit Format",
        type: "text",
        required: false,
        placeholder: "How artists will be credited",
      },
    ],
  },
  {
    id: "12",
    slug: "work-for-hire-agreement",
    name: "Work for Hire Agreement",
    description: "Agreement for commissioned creative work where the client owns all rights.",
    category: "Production",
    pdfUrl: "/contracts/work-for-hire-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      { id: "creator_name", name: "creator_name", label: "Creator Name", type: "text", required: false },
      { id: "creator_address", name: "creator_address", label: "Creator Address", type: "textarea", required: false },
      {
        id: "work_description",
        name: "work_description",
        label: "Work Description",
        type: "textarea",
        required: false,
        description: "Detailed description of the work to be created",
      },
      {
        id: "deliverables",
        name: "deliverables",
        label: "Deliverables",
        type: "textarea",
        required: false,
        description: "List all deliverables expected",
      },
      { id: "delivery_date", name: "delivery_date", label: "Delivery Date", type: "date", required: false },
      { id: "total_fee", name: "total_fee", label: "Total Fee", type: "currency", required: false },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
      },
      {
        id: "revision_rounds",
        name: "revision_rounds",
        label: "Number of Revision Rounds",
        type: "number",
        required: false,
      },
      {
        id: "additional_revision_rate",
        name: "additional_revision_rate",
        label: "Additional Revision Rate",
        type: "currency",
        required: false,
      },
    ],
  },
]

export function getContractBySlug(slug: string): ContractTemplate | undefined {
  return contractTemplates.find((contract) => contract.slug === slug)
}

export function getContractsByCategory(category: string): ContractTemplate[] {
  return contractTemplates.filter((contract) => contract.category === category)
}

export function getAllCategories(): string[] {
  return [...new Set(contractTemplates.map((contract) => contract.category))]
}
