export interface ContractTemplate {
  id: string
  slug: string
  name: string
  description: string
  category: string
  fields: ContractField[]
  pdfUrl: string
}

// Category images mapping with beautiful stock photos
export const categoryImages: Record<string, string> = {
  Marketing: "https://images.unsplash.com/photo-1557838923-2985c318be48?w=800&h=600&fit=crop",
  Production: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=800&h=600&fit=crop",
  Management: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=800&h=600&fit=crop",
  Recording: "https://images.unsplash.com/photo-1598653222000-6b7b7a552625?w=800&h=600&fit=crop",
  Sponsorship: "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800&h=600&fit=crop",
  Performance: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=600&fit=crop",
  Collaboration: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=600&fit=crop",
  Licensing: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop",
  Representation: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop",
  Business: "https://images.unsplash.com/photo-1664575602554-2087b04935a5?w=800&h=600&fit=crop",
  Release: "https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?w=800&h=600&fit=crop",
}

// Category gradient colors for enhanced visual appeal
export const categoryColors: Record<string, { from: string; to: string }> = {
  Marketing: { from: "#FF6B6B", to: "#FF8E53" },
  Production: { from: "#4ECDC4", to: "#44A08D" },
  Management: { from: "#A8E6CF", to: "#3BB78F" },
  Recording: { from: "#C471ED", to: "#F64F59" },
  Sponsorship: { from: "#FFA07A", to: "#FF6347" },
  Performance: { from: "#667EEA", to: "#764BA2" },
  Collaboration: { from: "#FFD89B", to: "#FF6B6B" },
  Licensing: { from: "#89CFF0", to: "#4A90E2" },
  Representation: { from: "#48C6EF", to: "#6F86D6" },
  Business: { from: "#5E60CE", to: "#7B2CBF" },
  Release: { from: "#FF6B9D", to: "#C239B3" },
}

export interface ContractField {
  id: string
  name: string
  label: string
  type: "text" | "email" | "date" | "number" | "textarea" | "select" | "currency" | "percentage"
  placeholder?: string
  description?: string
  required: boolean
  options?: string[]
}

export const contractTemplates: ContractTemplate[] = [
  {
    id: "1",
    slug: "influencer-agreement",
    name: "Artist Influencer Agreement",
    description:
      "A sponsorship agreement between a sponsor and an influencer for promoting goods through social media channels.",
    category: "Marketing",
    pdfUrl: "/contracts/influencer-agreement.pdf",
    fields: [
      {
        id: "effective_date",
        name: "effective_date",
        label: "Effective Date",
        type: "date",
        required: false,
        description: "The date this agreement becomes effective",
      },
      {
        id: "sponsor_name",
        name: "sponsor_name",
        label: "Sponsor Name",
        type: "text",
        required: false,
        placeholder: "Enter sponsor/company name",
      },
      {
        id: "sponsor_state",
        name: "sponsor_state",
        label: "Sponsor State of Incorporation",
        type: "text",
        required: false,
        placeholder: "e.g., Delaware",
      },
      {
        id: "sponsor_address",
        name: "sponsor_address",
        label: "Sponsor Address",
        type: "textarea",
        required: false,
        placeholder: "Full business address",
      },
      { id: "sponsor_email", name: "sponsor_email", label: "Sponsor Email", type: "email", required: false },
      { id: "influencer_name", name: "influencer_name", label: "Influencer Name", type: "text", required: false },
      {
        id: "influencer_address",
        name: "influencer_address",
        label: "Influencer Address",
        type: "textarea",
        required: false,
      },
      { id: "influencer_email", name: "influencer_email", label: "Influencer Email", type: "email", required: false },
      {
        id: "goods_description",
        name: "goods_description",
        label: "Description of Goods",
        type: "textarea",
        required: false,
        description: "Describe the products/goods being promoted",
      },
      {
        id: "social_platforms",
        name: "social_platforms",
        label: "Social Media Platforms",
        type: "textarea",
        required: false,
        placeholder: "e.g., Instagram, TikTok, YouTube",
      },
      {
        id: "display_channels",
        name: "display_channels",
        label: "Display Channels",
        type: "textarea",
        required: false,
        description: "Channels where goods will be displayed",
      },
      { id: "termination_date", name: "termination_date", label: "Termination Date", type: "date", required: false },
      {
        id: "specific_terms",
        name: "specific_terms",
        label: "Specific Terms",
        type: "textarea",
        required: false,
        description: "Any additional specific terms for the sponsorship",
      },
      { id: "payment_amount", name: "payment_amount", label: "Payment Amount", type: "currency", required: false },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
        description: "When and how payments will be made",
      },
      {
        id: "jurisdiction_county",
        name: "jurisdiction_county",
        label: "Jurisdiction County",
        type: "text",
        required: false,
        placeholder: "County for legal jurisdiction",
      },
    ],
  },
  {
    id: "2",
    slug: "production-agreement",
    name: "Music Production Agreement",
    description: "Agreement between a music producer and client for the production of music recordings.",
    category: "Production",
    pdfUrl: "/contracts/production-agreement.pdf",
    fields: [
      { id: "state", name: "state", label: "State", type: "text", required: false, placeholder: "e.g., California" },
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "producer_name", name: "producer_name", label: "Producer Name", type: "text", required: false },
      {
        id: "producer_address",
        name: "producer_address",
        label: "Producer Address",
        type: "textarea",
        required: false,
      },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      {
        id: "production_services",
        name: "production_services",
        label: "Production Services",
        type: "textarea",
        required: false,
        description: "Describe the specific production services to be provided",
      },
      { id: "commencement_date", name: "commencement_date", label: "Commencement Date", type: "date", required: false },
      { id: "fixed_fee", name: "fixed_fee", label: "Fixed Fee", type: "currency", required: false },
      {
        id: "specifications",
        name: "specifications",
        label: "Project Specifications",
        type: "textarea",
        required: false,
        description: "Required specifications for the project",
      },
      {
        id: "invoice_period",
        name: "invoice_period",
        label: "Invoice Payment Period",
        type: "text",
        required: false,
        placeholder: "e.g., 30 days",
      },
      {
        id: "payment_method",
        name: "payment_method",
        label: "Payment Method",
        type: "text",
        required: false,
        placeholder: "e.g., Bank transfer, PayPal",
      },
      {
        id: "late_interest_rate",
        name: "late_interest_rate",
        label: "Late Payment Interest Rate",
        type: "percentage",
        required: false,
      },
      {
        id: "royalties",
        name: "royalties",
        label: "Royalties",
        type: "textarea",
        required: false,
        description: "Describe any royalty arrangements",
      },
      { id: "producer_email", name: "producer_email", label: "Producer Email", type: "email", required: false },
      { id: "client_email", name: "client_email", label: "Client Email", type: "email", required: false },
    ],
  },
  {
    id: "3",
    slug: "artist-management-agreement",
    name: "Artist Management Agreement",
    description: "Comprehensive agreement between an artist and manager for career management services.",
    category: "Management",
    pdfUrl: "/contracts/artist-management-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "manager_name", name: "manager_name", label: "Manager Name", type: "text", required: false },
      {
        id: "initial_term",
        name: "initial_term",
        label: "Initial Term",
        type: "text",
        required: false,
        placeholder: "e.g., 6 months",
      },
      {
        id: "option_periods",
        name: "option_periods",
        label: "Option Periods",
        type: "text",
        required: false,
        placeholder: "e.g., Two 3-year periods",
      },
      {
        id: "commission_rate",
        name: "commission_rate",
        label: "Commission Rate",
        type: "percentage",
        required: false,
        placeholder: "e.g., 20%",
      },
      {
        id: "expense_approval_limit",
        name: "expense_approval_limit",
        label: "Expense Approval Limit",
        type: "currency",
        required: false,
        description: "Amount above which artist approval is needed",
      },
      {
        id: "post_term_commission_rate",
        name: "post_term_commission_rate",
        label: "Post-Term Commission Rate",
        type: "percentage",
        required: false,
      },
      {
        id: "post_term_period",
        name: "post_term_period",
        label: "Post-Term Period",
        type: "text",
        required: false,
        placeholder: "e.g., 1 year",
      },
      {
        id: "notice_days",
        name: "notice_days",
        label: "Notice Period (Days)",
        type: "number",
        required: false,
        placeholder: "e.g., 30",
      },
      {
        id: "arbitration_location",
        name: "arbitration_location",
        label: "Arbitration Location",
        type: "text",
        required: false,
      },
      {
        id: "governing_law_state",
        name: "governing_law_state",
        label: "Governing Law State",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "4",
    slug: "artist-label-agreement",
    name: "Artist Recording Contract",
    description: "Recording contract between an artist and a record label for producing commercial sound records.",
    category: "Recording",
    pdfUrl: "/contracts/artist-label-agreement.pdf",
    fields: [
      { id: "agreement_day", name: "agreement_day", label: "Agreement Day", type: "number", required: false },
      { id: "agreement_month", name: "agreement_month", label: "Agreement Month", type: "text", required: false },
      { id: "agreement_year", name: "agreement_year", label: "Agreement Year", type: "number", required: false },
      { id: "company_name", name: "company_name", label: "Company/Label Name", type: "text", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      {
        id: "agreement_period",
        name: "agreement_period",
        label: "Agreement Period",
        type: "text",
        required: false,
        placeholder: "e.g., 2 years",
      },
      {
        id: "minimum_selections",
        name: "minimum_selections",
        label: "Minimum Selections to Record",
        type: "number",
        required: false,
      },
      {
        id: "royalty_cents",
        name: "royalty_cents",
        label: "Royalty (Cents per Record)",
        type: "number",
        required: false,
      },
      {
        id: "payment_period_1",
        name: "payment_period_1",
        label: "First Payment Period Month",
        type: "text",
        required: false,
      },
      {
        id: "payment_period_1_end",
        name: "payment_period_1_end",
        label: "First Period End Date",
        type: "text",
        required: false,
      },
      {
        id: "payment_period_2",
        name: "payment_period_2",
        label: "Second Payment Period Month",
        type: "text",
        required: false,
      },
      {
        id: "payment_period_2_end",
        name: "payment_period_2_end",
        label: "Second Period End Date",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "5",
    slug: "sponsorship-agreement",
    name: "Sponsorship Agreement",
    description: "Agreement between an event organizer and sponsor for event sponsorship with promotional rights.",
    category: "Sponsorship",
    pdfUrl: "/contracts/sponsorship-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "organizer_name", name: "organizer_name", label: "Organizer Name", type: "text", required: false },
      { id: "organizer_state", name: "organizer_state", label: "Organizer State", type: "text", required: false },
      {
        id: "organizer_address",
        name: "organizer_address",
        label: "Organizer Address",
        type: "textarea",
        required: false,
      },
      { id: "sponsor_name", name: "sponsor_name", label: "Sponsor Name", type: "text", required: false },
      { id: "sponsor_state", name: "sponsor_state", label: "Sponsor State", type: "text", required: false },
      { id: "sponsor_address", name: "sponsor_address", label: "Sponsor Address", type: "textarea", required: false },
      { id: "event_type", name: "event_type", label: "Event Type", type: "text", required: false },
      { id: "event_time", name: "event_time", label: "Event Time/Date", type: "text", required: false },
      { id: "event_location", name: "event_location", label: "Event Location", type: "text", required: false },
      { id: "event_name", name: "event_name", label: "Event Name", type: "text", required: false },
      {
        id: "sponsorship_fee",
        name: "sponsorship_fee",
        label: "Total Sponsorship Fee",
        type: "currency",
        required: false,
      },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
      },
      { id: "term_end_date", name: "term_end_date", label: "Term End Date", type: "date", required: false },
    ],
  },
  {
    id: "6",
    slug: "band-booking-agreement",
    name: "Band Booking Agreement",
    description: "Performance contract between a band and venue/operator for live performances.",
    category: "Performance",
    pdfUrl: "/contracts/band-booking-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "operator_name", name: "operator_name", label: "Operator/Venue Name", type: "text", required: false },
      { id: "band_name", name: "band_name", label: "Band Name", type: "text", required: false },
      { id: "venue_name", name: "venue_name", label: "Venue Name", type: "text", required: false },
      { id: "venue_address", name: "venue_address", label: "Venue Address", type: "textarea", required: false },
      { id: "show_date", name: "show_date", label: "Show Date", type: "date", required: false },
      {
        id: "show_time",
        name: "show_time",
        label: "Show Time",
        type: "text",
        required: false,
        placeholder: "e.g., 9 PM",
      },
      {
        id: "minimum_duration",
        name: "minimum_duration",
        label: "Minimum Performance Duration (minutes)",
        type: "number",
        required: false,
      },
      { id: "total_fee", name: "total_fee", label: "Total Fee", type: "currency", required: false },
      { id: "payment_method", name: "payment_method", label: "Payment Method", type: "text", required: false },
      { id: "guest_tickets", name: "guest_tickets", label: "Number of Guest Tickets", type: "number", required: false },
      { id: "meals_provided", name: "meals_provided", label: "Meals/Buyout Details", type: "text", required: false },
      {
        id: "buyout_amount",
        name: "buyout_amount",
        label: "Buyout Amount Per Person",
        type: "currency",
        required: false,
      },
    ],
  },
  {
    id: "7",
    slug: "artist-venue-agreement",
    name: "Artist/Venue Agreement",
    description: "Comprehensive agreement between an artist and venue for performances at events.",
    category: "Performance",
    pdfUrl: "/contracts/artist-venue-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "venue_name", name: "venue_name", label: "Venue Name", type: "text", required: false },
      {
        id: "venue_organisation",
        name: "venue_organisation",
        label: "Venue Organisation",
        type: "text",
        required: false,
      },
      { id: "venue_address", name: "venue_address", label: "Venue Address", type: "textarea", required: false },
      { id: "venue_abn", name: "venue_abn", label: "Venue ABN", type: "text", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "artist_address", name: "artist_address", label: "Artist Address", type: "textarea", required: false },
      {
        id: "artist_contact_mobile",
        name: "artist_contact_mobile",
        label: "Artist Mobile",
        type: "text",
        required: false,
      },
      {
        id: "artist_contact_email",
        name: "artist_contact_email",
        label: "Artist Email",
        type: "email",
        required: false,
      },
      {
        id: "artist_representative",
        name: "artist_representative",
        label: "Artist Representative Name",
        type: "text",
        required: false,
      },
      { id: "performance_date", name: "performance_date", label: "Performance Date", type: "date", required: false },
      {
        id: "performance_duration",
        name: "performance_duration",
        label: "Performance Duration",
        type: "text",
        required: false,
      },
      { id: "fee_amount", name: "fee_amount", label: "Artist Fee", type: "currency", required: false },
      {
        id: "venue_manager_details",
        name: "venue_manager_details",
        label: "Venue Manager Details",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "8",
    slug: "dj-booking-agreement",
    name: "DJ Booking Agreement",
    description: "Service agreement between a DJ and client for DJ services at events.",
    category: "Performance",
    pdfUrl: "/contracts/dj-booking-agreement.pdf",
    fields: [
      { id: "state", name: "state", label: "State", type: "text", required: false },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      { id: "dj_name", name: "dj_name", label: "DJ Name", type: "text", required: false },
      { id: "dj_address", name: "dj_address", label: "DJ Address", type: "textarea", required: false },
      { id: "event_date", name: "event_date", label: "Event Date", type: "date", required: false },
      { id: "event_time", name: "event_time", label: "Event Time", type: "text", required: false },
      {
        id: "services_description",
        name: "services_description",
        label: "Services Description",
        type: "textarea",
        required: false,
      },
      { id: "total_hours", name: "total_hours", label: "Total Hours", type: "number", required: false },
      { id: "setup_time", name: "setup_time", label: "Setup Time Before Event", type: "text", required: false },
      { id: "venue_location", name: "venue_location", label: "Venue Location", type: "textarea", required: false },
      {
        id: "payment_structure",
        name: "payment_structure",
        label: "Payment Structure",
        type: "textarea",
        required: false,
      },
      { id: "retainer_fee", name: "retainer_fee", label: "Retainer Fee", type: "currency", required: false },
      {
        id: "overtime_rate",
        name: "overtime_rate",
        label: "Overtime Rate (per hour)",
        type: "currency",
        required: false,
      },
      { id: "late_fee", name: "late_fee", label: "Late Payment Fee", type: "currency", required: false },
      {
        id: "cancellation_notice",
        name: "cancellation_notice",
        label: "Cancellation Notice Period",
        type: "text",
        required: false,
      },
      {
        id: "cancellation_penalty",
        name: "cancellation_penalty",
        label: "Cancellation Penalty",
        type: "currency",
        required: false,
      },
    ],
  },
  {
    id: "9",
    slug: "agent-agreement",
    name: "Artist-Agent Agreement",
    description: "Agreement between an artist and agent for representation and marketing of artistic work.",
    category: "Representation",
    pdfUrl: "/contracts/agent-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "artist_address", name: "artist_address", label: "Artist Address", type: "textarea", required: false },
      { id: "agent_name", name: "agent_name", label: "Agent Name", type: "text", required: false },
      { id: "agent_address", name: "agent_address", label: "Agent Address", type: "textarea", required: false },
      { id: "agent_company", name: "agent_company", label: "Agent Company", type: "text", required: false },
      {
        id: "territory",
        name: "territory",
        label: "Territory",
        type: "text",
        required: false,
        placeholder: "e.g., United States, Worldwide",
      },
      {
        id: "commission_rate",
        name: "commission_rate",
        label: "Commission Rate",
        type: "percentage",
        required: false,
      },
      { id: "agreement_term", name: "agreement_term", label: "Agreement Term", type: "text", required: false },
      {
        id: "termination_notice",
        name: "termination_notice",
        label: "Termination Notice Period",
        type: "text",
        required: false,
      },
      {
        id: "governing_law_state",
        name: "governing_law_state",
        label: "Governing Law State",
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "10",
    slug: "licensing-agreement",
    name: "Music Licensing Agreement",
    description: "Agreement for licensing music rights between a licensor and licensee.",
    category: "Licensing",
    pdfUrl: "/contracts/licensing-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "licensor_name", name: "licensor_name", label: "Licensor Name", type: "text", required: false },
      {
        id: "licensor_address",
        name: "licensor_address",
        label: "Licensor Address",
        type: "textarea",
        required: false,
      },
      { id: "licensee_name", name: "licensee_name", label: "Licensee Name", type: "text", required: false },
      {
        id: "licensee_address",
        name: "licensee_address",
        label: "Licensee Address",
        type: "textarea",
        required: false,
      },
      { id: "work_title", name: "work_title", label: "Work Title", type: "text", required: false },
      {
        id: "work_description",
        name: "work_description",
        label: "Work Description",
        type: "textarea",
        required: false,
      },
      {
        id: "license_type",
        name: "license_type",
        label: "License Type",
        type: "text",
        required: false,
        placeholder: "e.g., Exclusive, Non-exclusive",
      },
      { id: "territory", name: "territory", label: "Territory", type: "text", required: false },
      { id: "license_fee", name: "license_fee", label: "License Fee", type: "currency", required: false },
      { id: "royalty_rate", name: "royalty_rate", label: "Royalty Rate", type: "percentage", required: false },
      { id: "license_term", name: "license_term", label: "License Term", type: "text", required: false },
      {
        id: "permitted_uses",
        name: "permitted_uses",
        label: "Permitted Uses",
        type: "textarea",
        required: false,
        description: "Describe how the licensed work may be used",
      },
    ],
  },
  {
    id: "11",
    slug: "collaboration-agreement",
    name: "Artist Collaboration Agreement",
    description: "Agreement between multiple artists for collaborative creative projects.",
    category: "Collaboration",
    pdfUrl: "/contracts/collaboration-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "artist_1_name", name: "artist_1_name", label: "First Artist Name", type: "text", required: false },
      {
        id: "artist_1_address",
        name: "artist_1_address",
        label: "First Artist Address",
        type: "textarea",
        required: false,
      },
      { id: "artist_2_name", name: "artist_2_name", label: "Second Artist Name", type: "text", required: false },
      {
        id: "artist_2_address",
        name: "artist_2_address",
        label: "Second Artist Address",
        type: "textarea",
        required: false,
      },
      {
        id: "project_description",
        name: "project_description",
        label: "Project Description",
        type: "textarea",
        required: false,
      },
      {
        id: "artist_1_contribution",
        name: "artist_1_contribution",
        label: "First Artist Contribution",
        type: "textarea",
        required: false,
      },
      {
        id: "artist_2_contribution",
        name: "artist_2_contribution",
        label: "Second Artist Contribution",
        type: "textarea",
        required: false,
      },
      {
        id: "ownership_split",
        name: "ownership_split",
        label: "Ownership Split",
        type: "text",
        required: false,
        placeholder: "e.g., 50/50",
      },
      {
        id: "revenue_split",
        name: "revenue_split",
        label: "Revenue Split",
        type: "text",
        required: false,
        placeholder: "e.g., 50/50",
      },
      { id: "project_deadline", name: "project_deadline", label: "Project Deadline", type: "date", required: false },
      {
        id: "credit_format",
        name: "credit_format",
        label: "Credit Format",
        type: "text",
        required: false,
        placeholder: "How artists will be credited",
      },
    ],
  },
  {
    id: "12",
    slug: "work-for-hire-agreement",
    name: "Work for Hire Agreement",
    description: "Agreement for commissioned creative work where the client owns all rights.",
    category: "Production",
    pdfUrl: "/contracts/work-for-hire-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      { id: "creator_name", name: "creator_name", label: "Creator Name", type: "text", required: false },
      { id: "creator_address", name: "creator_address", label: "Creator Address", type: "textarea", required: false },
      {
        id: "work_description",
        name: "work_description",
        label: "Work Description",
        type: "textarea",
        required: false,
        description: "Detailed description of the work to be created",
      },
      {
        id: "deliverables",
        name: "deliverables",
        label: "Deliverables",
        type: "textarea",
        required: false,
        description: "List all deliverables expected",
      },
      { id: "delivery_date", name: "delivery_date", label: "Delivery Date", type: "date", required: false },
      { id: "total_fee", name: "total_fee", label: "Total Fee", type: "currency", required: false },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
      },
      {
        id: "revision_rounds",
        name: "revision_rounds",
        label: "Number of Revision Rounds",
        type: "number",
        required: false,
      },
      {
        id: "additional_revision_rate",
        name: "additional_revision_rate",
        label: "Additional Revision Rate",
        type: "currency",
        required: false,
      },
    ],
  },

  {
    id: "13",
    slug: "master-producer-talent-agreement",
    name: "Master Producer-Talent Agreement",
    description:
      "Agreement between a music producer and talent for master recording production, including royalty arrangements and ownership rights.",
    category: "Production",
    pdfUrl: "/contracts/master-producer-talent-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "producer_name", name: "producer_name", label: "Producer Name", type: "text", required: false },
      {
        id: "producer_address",
        name: "producer_address",
        label: "Producer Address",
        type: "textarea",
        required: false,
      },
      { id: "talent_name", name: "talent_name", label: "Talent/Artist Name", type: "text", required: false },
      { id: "talent_address", name: "talent_address", label: "Talent Address", type: "textarea", required: false },
      { id: "project_title", name: "project_title", label: "Project/Album Title", type: "text", required: false },
      { id: "number_of_tracks", name: "number_of_tracks", label: "Number of Tracks", type: "number", required: false },
      {
        id: "recording_budget",
        name: "recording_budget",
        label: "Recording Budget",
        type: "currency",
        required: false,
      },
      { id: "producer_fee", name: "producer_fee", label: "Producer Fee", type: "currency", required: false },
      {
        id: "producer_royalty",
        name: "producer_royalty",
        label: "Producer Royalty Percentage",
        type: "percentage",
        required: false,
      },
      {
        id: "talent_royalty",
        name: "talent_royalty",
        label: "Talent Royalty Percentage",
        type: "percentage",
        required: false,
      },
      { id: "advance_amount", name: "advance_amount", label: "Advance Amount", type: "currency", required: false },
      { id: "delivery_date", name: "delivery_date", label: "Delivery Date", type: "date", required: false },
      {
        id: "master_ownership",
        name: "master_ownership",
        label: "Master Ownership Split",
        type: "text",
        required: false,
        placeholder: "e.g., 50/50",
      },
      {
        id: "territory",
        name: "territory",
        label: "Territory",
        type: "text",
        required: false,
        placeholder: "e.g., Worldwide",
      },
      {
        id: "term_length",
        name: "term_length",
        label: "Term Length",
        type: "text",
        required: false,
        placeholder: "e.g., 5 years",
      },
    ],
  },
  {
    id: "14",
    slug: "studio-time-contract",
    name: "Studio Time Contract",
    description:
      "Agreement for booking and using recording studio facilities, including rates, cancellation policies, and studio rules.",
    category: "Production",
    pdfUrl: "/contracts/studio-time-contract.pdf",
    fields: [
      { id: "contract_date", name: "contract_date", label: "Contract Date", type: "date", required: false },
      { id: "studio_name", name: "studio_name", label: "Studio Name", type: "text", required: false },
      { id: "studio_address", name: "studio_address", label: "Studio Address", type: "textarea", required: false },
      { id: "client_name", name: "client_name", label: "Client Name", type: "text", required: false },
      { id: "client_address", name: "client_address", label: "Client Address", type: "textarea", required: false },
      { id: "client_phone", name: "client_phone", label: "Client Phone", type: "text", required: false },
      { id: "client_email", name: "client_email", label: "Client Email", type: "email", required: false },
      { id: "session_date", name: "session_date", label: "Session Date", type: "date", required: false },
      { id: "start_time", name: "start_time", label: "Start Time", type: "text", required: false },
      { id: "end_time", name: "end_time", label: "End Time", type: "text", required: false },
      { id: "hourly_rate", name: "hourly_rate", label: "Hourly Rate", type: "currency", required: false },
      { id: "total_hours", name: "total_hours", label: "Total Hours Booked", type: "number", required: false },
      { id: "deposit_amount", name: "deposit_amount", label: "Deposit Amount", type: "currency", required: false },
      {
        id: "engineer_included",
        name: "engineer_included",
        label: "Engineer Included",
        type: "text",
        required: false,
        placeholder: "Yes/No",
      },
      {
        id: "engineer_rate",
        name: "engineer_rate",
        label: "Engineer Rate (if separate)",
        type: "currency",
        required: false,
      },
      {
        id: "cancellation_notice",
        name: "cancellation_notice",
        label: "Cancellation Notice Required",
        type: "text",
        required: false,
        placeholder: "e.g., 48 hours",
      },
      {
        id: "cancellation_fee",
        name: "cancellation_fee",
        label: "Cancellation Fee",
        type: "currency",
        required: false,
      },
    ],
  },
  {
    id: "15",
    slug: "artist-label-recording-agreement",
    name: "Artist/Label Recording Agreement",
    description:
      "Comprehensive recording contract between an artist and record label covering recording commitment, royalties, advances, and rights.",
    category: "Recording",
    pdfUrl: "/contracts/artist-label-recording-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "label_name", name: "label_name", label: "Label Name", type: "text", required: false },
      { id: "label_address", name: "label_address", label: "Label Address", type: "textarea", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "artist_legal_name", name: "artist_legal_name", label: "Artist Legal Name", type: "text", required: false },
      { id: "artist_address", name: "artist_address", label: "Artist Address", type: "textarea", required: false },
      {
        id: "initial_term",
        name: "initial_term",
        label: "Initial Term",
        type: "text",
        required: false,
        placeholder: "e.g., 1 year",
      },
      {
        id: "option_periods",
        name: "option_periods",
        label: "Option Periods",
        type: "text",
        required: false,
        placeholder: "e.g., 4 additional 1-year periods",
      },
      {
        id: "recording_commitment",
        name: "recording_commitment",
        label: "Recording Commitment",
        type: "text",
        required: false,
        placeholder: "e.g., 1 album per period",
      },
      {
        id: "minimum_tracks",
        name: "minimum_tracks",
        label: "Minimum Tracks per Album",
        type: "number",
        required: false,
      },
      { id: "recording_fund", name: "recording_fund", label: "Recording Fund", type: "currency", required: false },
      { id: "artist_advance", name: "artist_advance", label: "Artist Advance", type: "currency", required: false },
      { id: "royalty_rate", name: "royalty_rate", label: "Royalty Rate", type: "percentage", required: false },
      {
        id: "territory",
        name: "territory",
        label: "Territory",
        type: "text",
        required: false,
        placeholder: "e.g., Worldwide",
      },
      {
        id: "distribution_rights",
        name: "distribution_rights",
        label: "Distribution Rights",
        type: "textarea",
        required: false,
      },
      {
        id: "marketing_commitment",
        name: "marketing_commitment",
        label: "Marketing Commitment",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "16",
    slug: "split-sheet",
    name: "Split Sheet Agreement",
    description:
      "Document for recording the ownership percentages and contributions of all collaborators on a musical composition.",
    category: "Collaboration",
    pdfUrl: "/contracts/split-sheet.pdf",
    fields: [
      { id: "song_title", name: "song_title", label: "Song Title", type: "text", required: false },
      { id: "recording_date", name: "recording_date", label: "Recording Date", type: "date", required: false },
      {
        id: "contributor_1_name",
        name: "contributor_1_name",
        label: "Contributor 1 Name",
        type: "text",
        required: false,
      },
      {
        id: "contributor_1_role",
        name: "contributor_1_role",
        label: "Contributor 1 Role",
        type: "text",
        required: false,
        placeholder: "e.g., Lyrics, Music, Production",
      },
      {
        id: "contributor_1_percentage",
        name: "contributor_1_percentage",
        label: "Contributor 1 Percentage",
        type: "percentage",
        required: false,
      },
      {
        id: "contributor_1_pro",
        name: "contributor_1_pro",
        label: "Contributor 1 PRO",
        type: "text",
        required: false,
        placeholder: "e.g., ASCAP, BMI, SESAC",
      },
      {
        id: "contributor_1_ipi",
        name: "contributor_1_ipi",
        label: "Contributor 1 IPI/CAE Number",
        type: "text",
        required: false,
      },
      {
        id: "contributor_2_name",
        name: "contributor_2_name",
        label: "Contributor 2 Name",
        type: "text",
        required: false,
      },
      {
        id: "contributor_2_role",
        name: "contributor_2_role",
        label: "Contributor 2 Role",
        type: "text",
        required: false,
      },
      {
        id: "contributor_2_percentage",
        name: "contributor_2_percentage",
        label: "Contributor 2 Percentage",
        type: "percentage",
        required: false,
      },
      { id: "contributor_2_pro", name: "contributor_2_pro", label: "Contributor 2 PRO", type: "text", required: false },
      {
        id: "contributor_2_ipi",
        name: "contributor_2_ipi",
        label: "Contributor 2 IPI/CAE Number",
        type: "text",
        required: false,
      },
      {
        id: "contributor_3_name",
        name: "contributor_3_name",
        label: "Contributor 3 Name",
        type: "text",
        required: false,
      },
      {
        id: "contributor_3_role",
        name: "contributor_3_role",
        label: "Contributor 3 Role",
        type: "text",
        required: false,
      },
      {
        id: "contributor_3_percentage",
        name: "contributor_3_percentage",
        label: "Contributor 3 Percentage",
        type: "percentage",
        required: false,
      },
      { id: "contributor_3_pro", name: "contributor_3_pro", label: "Contributor 3 PRO", type: "text", required: false },
      {
        id: "publisher_name",
        name: "publisher_name",
        label: "Publisher Name (if applicable)",
        type: "text",
        required: false,
      },
      { id: "isrc_code", name: "isrc_code", label: "ISRC Code", type: "text", required: false },
    ],
  },
  {
    id: "17",
    slug: "llc-operating-agreement",
    name: "LLC Operating Agreement (Music Label)",
    description:
      "Operating agreement for a music label structured as an LLC, covering member rights, profit distribution, and management.",
    category: "Business",
    pdfUrl: "/contracts/llc-operating-agreement.pdf",
    fields: [
      { id: "effective_date", name: "effective_date", label: "Effective Date", type: "date", required: false },
      { id: "llc_name", name: "llc_name", label: "LLC Name", type: "text", required: false },
      {
        id: "state_of_formation",
        name: "state_of_formation",
        label: "State of Formation",
        type: "text",
        required: false,
      },
      {
        id: "principal_address",
        name: "principal_address",
        label: "Principal Business Address",
        type: "textarea",
        required: false,
      },
      { id: "member_1_name", name: "member_1_name", label: "Member 1 Name", type: "text", required: false },
      {
        id: "member_1_address",
        name: "member_1_address",
        label: "Member 1 Address",
        type: "textarea",
        required: false,
      },
      {
        id: "member_1_contribution",
        name: "member_1_contribution",
        label: "Member 1 Capital Contribution",
        type: "currency",
        required: false,
      },
      {
        id: "member_1_ownership",
        name: "member_1_ownership",
        label: "Member 1 Ownership Percentage",
        type: "percentage",
        required: false,
      },
      { id: "member_2_name", name: "member_2_name", label: "Member 2 Name", type: "text", required: false },
      {
        id: "member_2_address",
        name: "member_2_address",
        label: "Member 2 Address",
        type: "textarea",
        required: false,
      },
      {
        id: "member_2_contribution",
        name: "member_2_contribution",
        label: "Member 2 Capital Contribution",
        type: "currency",
        required: false,
      },
      {
        id: "member_2_ownership",
        name: "member_2_ownership",
        label: "Member 2 Ownership Percentage",
        type: "percentage",
        required: false,
      },
      {
        id: "management_structure",
        name: "management_structure",
        label: "Management Structure",
        type: "text",
        required: false,
        placeholder: "Member-managed or Manager-managed",
      },
      {
        id: "profit_distribution",
        name: "profit_distribution",
        label: "Profit Distribution Schedule",
        type: "textarea",
        required: false,
      },
      {
        id: "fiscal_year_end",
        name: "fiscal_year_end",
        label: "Fiscal Year End",
        type: "text",
        required: false,
        placeholder: "e.g., December 31",
      },
      {
        id: "dissolution_terms",
        name: "dissolution_terms",
        label: "Dissolution Terms",
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "18",
    slug: "talent-release-form",
    name: "Talent Release Form",
    description:
      "Release form for talent appearing in recordings, videos, or promotional materials, granting usage rights to the producer.",
    category: "Release",
    pdfUrl: "/contracts/talent-release-form.pdf",
    fields: [
      { id: "release_date", name: "release_date", label: "Release Date", type: "date", required: false },
      { id: "talent_name", name: "talent_name", label: "Talent Name", type: "text", required: false },
      { id: "talent_address", name: "talent_address", label: "Talent Address", type: "textarea", required: false },
      { id: "talent_phone", name: "talent_phone", label: "Talent Phone", type: "text", required: false },
      { id: "talent_email", name: "talent_email", label: "Talent Email", type: "email", required: false },
      { id: "producer_name", name: "producer_name", label: "Producer/Company Name", type: "text", required: false },
      {
        id: "producer_address",
        name: "producer_address",
        label: "Producer Address",
        type: "textarea",
        required: false,
      },
      { id: "project_title", name: "project_title", label: "Project Title", type: "text", required: false },
      {
        id: "project_description",
        name: "project_description",
        label: "Project Description",
        type: "textarea",
        required: false,
      },
      { id: "recording_date", name: "recording_date", label: "Recording/Shoot Date", type: "date", required: false },
      {
        id: "recording_location",
        name: "recording_location",
        label: "Recording Location",
        type: "textarea",
        required: false,
      },
      {
        id: "compensation_amount",
        name: "compensation_amount",
        label: "Compensation Amount",
        type: "currency",
        required: false,
      },
      { id: "usage_rights", name: "usage_rights", label: "Usage Rights Granted", type: "textarea", required: false },
      {
        id: "territory",
        name: "territory",
        label: "Territory",
        type: "text",
        required: false,
        placeholder: "e.g., Worldwide",
      },
      {
        id: "term",
        name: "term",
        label: "Term/Duration",
        type: "text",
        required: false,
        placeholder: "e.g., In perpetuity",
      },
    ],
  },
  {
    id: "19",
    slug: "producer-composer-agreement",
    name: "Producer/Composer Agreement",
    description: "Agreement between a producer and composer for creating original musical compositions for a project.",
    category: "Production",
    pdfUrl: "/contracts/producer-composer-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "producer_name", name: "producer_name", label: "Producer Name", type: "text", required: false },
      { id: "producer_company", name: "producer_company", label: "Producer Company", type: "text", required: false },
      {
        id: "producer_address",
        name: "producer_address",
        label: "Producer Address",
        type: "textarea",
        required: false,
      },
      { id: "composer_name", name: "composer_name", label: "Composer Name", type: "text", required: false },
      {
        id: "composer_address",
        name: "composer_address",
        label: "Composer Address",
        type: "textarea",
        required: false,
      },
      { id: "project_title", name: "project_title", label: "Project Title", type: "text", required: false },
      {
        id: "project_type",
        name: "project_type",
        label: "Project Type",
        type: "text",
        required: false,
        placeholder: "e.g., Film, Album, Commercial",
      },
      {
        id: "composition_description",
        name: "composition_description",
        label: "Composition Description",
        type: "textarea",
        required: false,
      },
      { id: "delivery_date", name: "delivery_date", label: "Delivery Date", type: "date", required: false },
      { id: "composer_fee", name: "composer_fee", label: "Composer Fee", type: "currency", required: false },
      {
        id: "payment_schedule",
        name: "payment_schedule",
        label: "Payment Schedule",
        type: "textarea",
        required: false,
      },
      {
        id: "publishing_split",
        name: "publishing_split",
        label: "Publishing Split",
        type: "text",
        required: false,
        placeholder: "e.g., 50/50",
      },
      { id: "royalty_share", name: "royalty_share", label: "Royalty Share", type: "percentage", required: false },
      { id: "credit_language", name: "credit_language", label: "Credit Language", type: "text", required: false },
      {
        id: "revision_rounds",
        name: "revision_rounds",
        label: "Number of Revision Rounds",
        type: "number",
        required: false,
      },
    ],
  },
  {
    id: "20",
    slug: "video-release-form",
    name: "Video Release Form",
    description:
      "Release form for individuals appearing in music videos or visual content, authorizing the use of their likeness.",
    category: "Release",
    pdfUrl: "/contracts/video-release-form.pdf",
    fields: [
      { id: "release_date", name: "release_date", label: "Release Date", type: "date", required: false },
      { id: "participant_name", name: "participant_name", label: "Participant Name", type: "text", required: false },
      {
        id: "participant_address",
        name: "participant_address",
        label: "Participant Address",
        type: "textarea",
        required: false,
      },
      { id: "participant_phone", name: "participant_phone", label: "Participant Phone", type: "text", required: false },
      {
        id: "participant_email",
        name: "participant_email",
        label: "Participant Email",
        type: "email",
        required: false,
      },
      {
        id: "production_company",
        name: "production_company",
        label: "Production Company",
        type: "text",
        required: false,
      },
      {
        id: "production_address",
        name: "production_address",
        label: "Production Company Address",
        type: "textarea",
        required: false,
      },
      { id: "video_title", name: "video_title", label: "Video Title", type: "text", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist Name", type: "text", required: false },
      { id: "shoot_date", name: "shoot_date", label: "Shoot Date", type: "date", required: false },
      { id: "shoot_location", name: "shoot_location", label: "Shoot Location", type: "textarea", required: false },
      {
        id: "role_description",
        name: "role_description",
        label: "Role/Appearance Description",
        type: "textarea",
        required: false,
      },
      { id: "compensation", name: "compensation", label: "Compensation", type: "currency", required: false },
      {
        id: "usage_platforms",
        name: "usage_platforms",
        label: "Usage Platforms",
        type: "textarea",
        required: false,
        placeholder: "e.g., YouTube, TV, Social Media",
      },
      {
        id: "territory",
        name: "territory",
        label: "Territory",
        type: "text",
        required: false,
        placeholder: "e.g., Worldwide",
      },
      { id: "term", name: "term", label: "Term", type: "text", required: false, placeholder: "e.g., In perpetuity" },
    ],
  },
  {
    id: "21",
    slug: "performance-venue-agreement",
    name: "Performance Venue Agreement",
    description:
      "Comprehensive agreement between an artist/performer and venue for live performances including technical requirements and payment terms.",
    category: "Performance",
    pdfUrl: "/contracts/performance-venue-agreement.pdf",
    fields: [
      { id: "agreement_date", name: "agreement_date", label: "Agreement Date", type: "date", required: false },
      { id: "artist_name", name: "artist_name", label: "Artist/Performer Name", type: "text", required: false },
      {
        id: "artist_representative",
        name: "artist_representative",
        label: "Artist Representative",
        type: "text",
        required: false,
      },
      { id: "artist_address", name: "artist_address", label: "Artist Address", type: "textarea", required: false },
      { id: "artist_phone", name: "artist_phone", label: "Artist Phone", type: "text", required: false },
      { id: "artist_email", name: "artist_email", label: "Artist Email", type: "email", required: false },
      { id: "venue_name", name: "venue_name", label: "Venue Name", type: "text", required: false },
      { id: "venue_address", name: "venue_address", label: "Venue Address", type: "textarea", required: false },
      { id: "venue_contact", name: "venue_contact", label: "Venue Contact Person", type: "text", required: false },
      { id: "venue_phone", name: "venue_phone", label: "Venue Phone", type: "text", required: false },
      { id: "performance_date", name: "performance_date", label: "Performance Date", type: "date", required: false },
      { id: "load_in_time", name: "load_in_time", label: "Load-In Time", type: "text", required: false },
      { id: "soundcheck_time", name: "soundcheck_time", label: "Soundcheck Time", type: "text", required: false },
      { id: "performance_time", name: "performance_time", label: "Performance Time", type: "text", required: false },
      {
        id: "set_length",
        name: "set_length",
        label: "Set Length",
        type: "text",
        required: false,
        placeholder: "e.g., 90 minutes",
      },
      {
        id: "guarantee_amount",
        name: "guarantee_amount",
        label: "Guarantee Amount",
        type: "currency",
        required: false,
      },
      { id: "bonus_terms", name: "bonus_terms", label: "Bonus Terms", type: "textarea", required: false },
      { id: "ticket_price", name: "ticket_price", label: "Ticket Price", type: "currency", required: false },
      { id: "capacity", name: "capacity", label: "Venue Capacity", type: "number", required: false },
      {
        id: "technical_requirements",
        name: "technical_requirements",
        label: "Technical Requirements",
        type: "textarea",
        required: false,
      },
      {
        id: "hospitality_rider",
        name: "hospitality_rider",
        label: "Hospitality Rider",
        type: "textarea",
        required: false,
      },
    ],
  },
]

export function getContractBySlug(slug: string): ContractTemplate | undefined {
  return contractTemplates.find((contract) => contract.slug === slug)
}

export function getContractsByCategory(category: string): ContractTemplate[] {
  return contractTemplates.filter((contract) => contract.category === category)
}

export function getAllCategories(): string[] {
  return [...new Set(contractTemplates.map((contract) => contract.category))]
}

export const contracts = contractTemplates
